### PR TITLE
Update data.json (F4SE Mirror)

### PR DESCRIPTION
**Pull request by Scrivener07**
Added version controlled f4se mirror.

### CODE REVIEW

**Comment by Ortham** [comment]
I'm hesitant to add an unofficial mirror in place of the officially-hosted URL, especially as it doesn't contain anything not accessible via the existing link (not to say release diffs aren't potentially useful or interesting). Is there any indication that the F4SE team have given this mirror their blessing, or similar?

**Comment by Scrivener07** [comment]
No it doesnt have the explicit blessing of the F4SE team. I agree with your hesitation. Maybe there is a better way to add an f4se mirror? An new entry, a new url property of an entry?

**Comment by Ortham** [comment]
After more thought, I don't think buddah should be adding the link at all. I think it's out of scope to handle project mirrors, they should be publicised on the project's own pages. Also, an unofficial mirror isn't particularly notable - I could start mirroring F4SE, why not add mine too? If 10 people create mirrors, which get added? There's no strong differentiator between them.

For those reasons, I'm going to close this PR, thanks though.

**Comment by Scrivener07** [comment]
Good reasoning. Yes there are at least two other mirrors thats I know if.

**Pull request closed without merging**
